from __future__ import annotations

import subprocess
import unittest
from pathlib import Path

from stock_tracker.quant.data import DataSnapshotManifest, RawDataArtifact
from stock_tracker.quant.storage import OutcomeLedger


class TestSourceDistribution(unittest.TestCase):
    """Guard against source packages being present locally but omitted by Git."""

    def test_quant_data_contract_imports(self) -> None:
        self.assertTrue(callable(RawDataArtifact))
        self.assertTrue(callable(DataSnapshotManifest))
        self.assertTrue(callable(OutcomeLedger))

    def test_critical_quant_data_files_are_tracked(self) -> None:
        root = Path(__file__).resolve().parents[1]
        if not (root / ".git").exists():
            self.skipTest("source-distribution check requires a Git checkout")

        critical = (
            "tests/test_n4_review_closure.py",
            "docs/N4-REVIEW-CLOSURE-20260914.md",
            "stock_tracker/api/handlers.py",
            "stock_tracker/api/serializers.py",
            "stock_tracker/api/evidence_handlers.py",
            "stock_tracker/features/evidence_comparison.py",
            "stock_tracker/features/evidence_snapshot.py",
            "tests/test_evidence_comparison.py",
            "tests/test_evidence_diagnostic_api.py",
            "tests/test_quote_age_clock_basis.py",
            "scripts/run_evidence_comparison.py",
            "web/index.html",
            "web/js/app.js",
            "web/js/evidence_comparison.js",
            "web/css/evidence_comparison.css",
            "qa/ui/evidence_comparison_qa.cjs",
            "docs/EVIDENCE-COMPARISON-20260914-PLAN.md",
            "stock_tracker/features/horizon_research.py",
            "tests/test_horizon_research.py",
            "stock_tracker/features/horizon_cli.py",
            "tests/test_horizon_cli.py",
            "tests/test_n4_continuation_edges.py",
            "tests/test_evidence_http.py",
            "tests/test_evidence_recipe_identity.py",
            "docs/N4-CONTINUATION-20260914.md",
            "docs/N4-DECLARED-RESEARCH-RUNBOOK.md",
            ".gitattributes",
            "stock_tracker/collector/provider.py",
            "tests/test_runtime_https_policy.py",
            "tests/test_indicator_input_policy.py",
            "tests_quant/test_metric_input_policy.py",
            "tests/fixtures/numerical_baselines_v1.json",
            "docs/NUMERICAL-FOUNDATION-20260914.md",
            "docs/NUMERICAL-INTEGRATION-20260914.md",
            "stock_tracker/features/indicator_diagnostics.py",
            "stock_tracker/features/indicators.py",
            "stock_tracker/quant/evaluation/metrics.py",
            "scripts/run_numerical_baseline.py",
            "tests/fixtures/numerical_legacy_v1.json",
            "tests/test_numerical_baseline.py",
            "tests/test_indicator_baseline_vectors.py",
            "tests/test_indicator_diagnostics.py",
            "tests_quant/test_metric_contract_edges.py",
            "qa/ui/indicator_diagnostics_qa.cjs",
            "web/js/indicator_diagnostics.js",
            "web/css/indicator_diagnostics.css",
            "docs/NUMERICAL-BASELINE-20260914-PLAN.md",
            "stock_tracker/portfolio_planning/resources.py",
            "tests/test_planning_resources.py",
            "qa/ui/planning_lifecycle_qa.cjs",
            "tests/test_planning_recovery.py",
            "docs/MULTIHORIZON-CLOSURE-20260912.md",
            "stock_tracker/portfolio_planning/__init__.py",
            "stock_tracker/portfolio_planning/__main__.py",
            "stock_tracker/portfolio_planning/domain.py",
            "stock_tracker/portfolio_planning/store.py",
            "stock_tracker/api/planning_handlers.py",
            "tests/test_portfolio_planning.py",
            "tests/test_planning_api.py",
            "scripts/run_planning_integration.py",
            "web/js/planning.js",
            "web/css/planning.css",
            "qa/ui/planning_qa.cjs",
            "docs/MULTIHORIZON-P1-P3-IMPLEMENTATION.md",
            "docs/MULTIHORIZON-MANUAL-PLANNING-RUNBOOK.md",
            "docs/PRODUCT-TRADING-PROFILE-20260911.md",
            ".gitattributes",
            "docs/STAGE4G1-CHECKPOINT-A-IMPLEMENTATION.md",
            "docs/STAGE4G1-CHECKPOINT-B0-EVIDENCE-VOCABULARY-AND-PATH-CONTRACT.md",
            "docs/STAGE4G1-CHECKPOINT-B1-B3-MARKET-PATH-PIPELINE-DESIGN.md",
            "scripts/capture_quant_bars.py",
            "scripts/capture_hithink_bars.py",
            "scripts/capture_a_share_corporate_actions.py",
            "scripts/extract_a_share_corporate_actions.py",
            "scripts/materialize_adjusted_market_data.py",
            "scripts/reconcile_a_share_corporate_actions.py",
            "scripts/report_stage2g_market_bars.py",
            "scripts/build_stage2h_market_bar_acceptance.py",
            "scripts/report_stage2h_market_bar_acceptance.py",
            "scripts/ingest_outcome_ledger.py",
            "scripts/report_outcome_ledger.py",
            "scripts/runtime_migrate.py",
            "scripts/verify_free_stockdb_sidecar.py",
            "stock_tracker/collector/free_stockdb.py",
            "stock_tracker/collector/hithink_finance.py",
            "stock_tracker/collector/tencent.py",
            "stock_tracker/core/market_time.py",
            "stock_tracker/quant/core/big_trend.py",
            "stock_tracker/quant/core/classification.py",
            "stock_tracker/quant/core/corporate_actions.py",
            "stock_tracker/quant/core/events.py",
            "stock_tracker/quant/core/market_isolation.py",
            "stock_tracker/quant/core/outcomes.py",
            "stock_tracker/quant/data/__init__.py",
            "stock_tracker/quant/data/adjusted_market_data.py",
            "stock_tracker/quant/data/bar_artifact.py",
            "stock_tracker/quant/data/classification_adapter.py",
            "stock_tracker/quant/data/corporate_action_adapter.py",
            "stock_tracker/quant/data/corporate_action_extraction.py",
            "stock_tracker/quant/data/corporate_action_reconciliation.py",
            "stock_tracker/quant/data/free_stockdb_governance.py",
            "stock_tracker/quant/data/manifest.py",
            "stock_tracker/quant/data/market_bar_acceptance.py",
            "stock_tracker/quant/data/market_bar_golden.py",
            "stock_tracker/quant/data/market_bar_reconciliation.py",
            "stock_tracker/quant/evaluation/attribution.py",
            "stock_tracker/quant/evaluation/decision_quality.py",
            "stock_tracker/quant/evaluation/shadow_lifecycle.py",
            "stock_tracker/quant/research/replay.py",
            "stock_tracker/quant/storage/__init__.py",
            "stock_tracker/quant/storage/outcome_ledger.py",
            "stock_tracker/runtime_evidence/__init__.py",
            "stock_tracker/runtime_evidence/contracts.py",
            "stock_tracker/runtime_evidence/path_contracts.py",
            "stock_tracker/runtime_evidence/physical_store.py",
            "stock_tracker/runtime_evidence/physical_store_cli.py",
            "tests/test_physical_evidence_store.py",
            "tests/test_physical_evidence_cli.py",
            "docs/STAGE4G1-B1-PHYSICAL-STORAGE-IMPLEMENTATION-PLAN.md",
            "stock_tracker/runtime_evidence/source_snapshot_contracts.py",
            "stock_tracker/runtime_evidence/store.py",
            "stock_tracker/runtime_evidence/worker.py",
            "stock_tracker/storage/migrations_runtime/0001_runtime_evidence_outbox.sql",
            "stock_tracker/storage/migrations_runtime/0002_runtime_occurrence_identity.sql",
            "stock_tracker/storage/migrations_runtime/0003_runtime_delivery_binding_and_integrity.sql",
            "stock_tracker/storage/runtime_migrations.py",
            "stock_tracker/quant/storage/migrations/0004_corporate_action_identity.sql",
            "tests_quant/test_adjusted_market_data.py",
            "tests_quant/test_attribution.py",
            "tests_quant/test_big_trend.py",
            "tests_quant/test_classification.py",
            "tests_quant/test_classification_adapter.py",
            "tests_quant/test_corporate_actions.py",
            "tests_quant/test_corporate_action_adapter.py",
            "tests_quant/test_corporate_action_extraction.py",
            "tests_quant/test_corporate_action_reconciliation.py",
            "tests_quant/test_capture_hithink_bars_cli.py",
            "tests_quant/test_decision_quality.py",
            "tests_quant/test_events.py",
            "tests_quant/test_free_stockdb_governance.py",
            "tests_quant/test_market_isolation.py",
            "tests_quant/test_market_bar_acceptance.py",
            "tests_quant/test_market_bar_reconciliation.py",
            "tests_quant/test_outcomes.py",
            "tests_quant/test_outcome_ledger_cli.py",
            "tests_quant/test_outcome_ledger_codec.py",
            "tests_quant/test_outcome_ledger_scoreboard.py",
            "tests_quant/test_outcome_ledger_store.py",
            "tests_quant/test_replay.py",
            "tests_quant/test_shadow_lifecycle.py",
            "tests_quant/test_stage2g_market_bar_cli.py",
            "tests_quant/test_stage2h_market_bar_acceptance_cli.py",
            "tests_quant/fixtures/market_bar_golden/v1/manifest.json",
            "tests_quant/fixtures/market_bar_golden/v1/a/600519_eastmoney.json",
            "tests_quant/fixtures/market_bar_golden/v1/a/600519_tencent.json",
            "tests_quant/fixtures/market_bar_golden/v1/hk/00700_eastmoney.json",
            "tests_quant/fixtures/market_bar_golden/v1/hk/00700_tencent.json",
            "tests_quant/fixtures/market_bar_golden/v1/us/AAPL_eastmoney.json",
            "tests_quant/fixtures/market_bar_golden/v1/us/AAPL_tencent.json",
            "tests_quant/fixtures/market_bar_golden/v2/manifest.json",
            "tests_quant/fixtures/market_bar_golden/v2/a/600519_eastmoney.json",
            "tests_quant/fixtures/market_bar_golden/v2/a/600519_tencent.json",
            "tests_quant/fixtures/market_bar_golden/v2/hk/00700_eastmoney.json",
            "tests_quant/fixtures/market_bar_golden/v2/hk/00700_tencent.json",
            "tests_quant/fixtures/market_bar_golden/v2/us/AAPL_eastmoney.json",
            "tests_quant/fixtures/market_bar_golden/v2/us/AAPL_tencent.json",
            "tests/test_free_stockdb_provider.py",
            "tests/test_hithink_finance_provider.py",
            "tests/test_provider_research_request.py",
            "tests/test_market_source_snapshot_contracts.py",
            "tests/test_runtime_evidence.py",
            "tests/test_runtime_path_contracts.py",
        )
        for relative_path in critical:
            with self.subTest(path=relative_path):
                result = subprocess.run(
                    ["git", "ls-files", "--error-unmatch", relative_path],
                    cwd=root,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertEqual(
                    result.returncode,
                    0,
                    msg=(
                        f"critical source file is not tracked: {relative_path}\n"
                        f"stdout={result.stdout}\nstderr={result.stderr}"
                    ),
                )


if __name__ == "__main__":
    unittest.main()
